### ISSUE TITLE
Make whereis-collection return a set? 

### ISSUE THREAD

**Issue by jackfirth** [rmculpepper/racket-whereis#1]
Is the order of the paths returned by `whereis-collection` important to callers? If not (and assuming it doesn't return duplicate paths), what do you think about making it return a set instead of a list?

**Comment by rmculpepper** [comment]
The order is slightly significant, in that it puts `collects` paths before package paths. Aside from that, lists already satisfy `generic-set?`, so the results can be used as a set, but using a different set representation would just complicate things for people who don't care about the difference.

**Comment by jackfirth** [comment]
I was thinking more that it would be helpful for callers to _know_ that it has the semantics of returning a set. As a reader I had to scan the docs prose to figure out if there was some sort of sorting being done or not, and convince myself that duplicates would be silly. It's nice to not have to do that work when learning an API. For those who don't care about the difference, using `racket/sequence` seems like a good thing to encourage doing.

**Comment by rmculpepper** [comment]
I see your argument, but I think you are attempting to purchase a penny's worth of clarity with a nickel's worth of code and run-time complexity.
